### ISSUE TITLE
create_hypercube returns "-" in measure value

### ISSUE THREAD

**Issue by bhargavpatel431997** [qliknln/pyqlikengine#3]
below is my code 

`from QlikAPI.pyqlikengine import QixEngine`
`engine = QixEngine('ws://localhost:4848/app')`
`engine.open_app("C:\\Users\\xxxxx\\Documents\\Qlik\\Sense\\Apps\\Consumer Sales.qvf")`
`data, column_num = engine.create_hypercube(list_of_dimensions=["City"], list_of_measures=["Revenue"])`
`answer = engine.convert_hypercube_to_matrix(data,column_num)`
`print(answer)`

**issue is, matrix returns dimension values perfectly but in measure value it returns "-".**

Output:
`[['Compton', 'Memphis', 'Overland Park', 'St Louis Park', 'Tuscon', 'Mebane', 'Pearl', 'Anchorage', 'New Hampton', 'Libby', 'Milwaukie', 'North Highlands', 'Spokane', 'West Jordan', 'Livonia', 'Wester Chester','-'],['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-' ]]`

Any help, thanks!

Regards,
Bhargav Patel

**Comment by qliknln** [comment]
Hi Bhargav, thanks for reaching out.
I assume you're using the Sense Example app "Consumer Sales" and in that app, the "Revenue" parameter, used for the measure here, refers to a master item. Master items are stored in the Qlik Sense Repository and can therefore not be used this way since you work directly towards the Qlik Engine. You have to write the full expression.
So, for this case, if you replace "Revenue" with the underlying expression "Sum( [Sales Quantity]*[Sales Price])", I think you should be ok.

Br,
Niklas

**Comment by bhargavpatel431997** [comment]
Yeah, that worked thank you.
